spring.application.name=coopspace-backend
# dane do logowania do panelu na localhost:8080, haslo to ala
spring.security.user.name=admin
spring.security.user.password=$2a$10$.JHCVqS4ewZ4utrsWocNhuR1k8uloCvaYgBOc.Gah8PQ4sOLglRF2
# konfiguracja bazy danych
spring.datasource.url=jdbc:postgresql://localhost:5434/projekt_pz
spring.datasource.username=admin
spring.datasource.password=ala

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# brak szczegolowego komunikatu o braku danej trasy API
server.error.whitelabel.enabled=false

# włączenie automatycznej migracji przy starcie
spring.flyway.enabled=true

# wylaczenie wymagania pliku dockera w katalogu backendu przez spring boota
spring.docker.compose.skip.in-tests=false
spring.docker.compose.enabled=false

# konfiguracja JWT
application.security.jwt.secret-key=n2Cz8sMr8tJXq1yuvUvCSMGIuiT6WcgvxJMrjjCVAtA
application.security.jwt.expiration=86400000